name = "TriplotRecipes"
uuid = "808ab39a-a642-4abf-81ff-4cb34ebbffa3"
authors = ["Will Pazner <will.e.p@gmail.com>"]
version = "0.1.1"

[deps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
TriplotBase = "981d1d27-644d-49a2-9326-4793e63143c3"

[compat]
julia = "1"
RecipesBase = "1"
TriplotBase = "0.1"
